name: Main Workflow
on:
  push:
    branches:
      - main

      
jobs:
  trigger-shared-workflow:
    uses: Auditore8/GHA/.github/workflows/shared-workflow.yml@main
    with:
      username: 'Tom'


